"""Loop report generation: LOOP-<episode-id>.md."""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from .models import LoopEpisode, LoopIteration, LoopSignal, LoopStatus


def render_report(episode: LoopEpisode, project_dir: Path) -> str:
    """Render a LOOP-<episode-id>.md report."""
    lines = [
        f"# LOOP-{episode.episode_id}",
        "",
        f"- **Episode**: {episode.episode_id}",
        f"- **Project**: {episode.slug}",
        f"- **Status**: `{episode.status.value}`",
        f"- **Root Cause**: {episode.root_cause}",
        f"- **Created**: {episode.created_at}",
        f"- **Updated**: {episode.updated_at}",
        f"- **Policy**: max_iterations={episode.policy.max_iterations}, "
        f"switch_delta={episode.policy.switch_score_delta}, "
        f"min_confidence={episode.policy.minimum_confidence.value}",
        "",
        "## Iterations",
        "",
    ]
    if not episode.iterations:
        lines.append("No iterations recorded yet.")
        lines.append("")
    else:
        for it in episode.iterations:
            lines.extend([
                f"### Iteration {it.index}: {it.action}",
                "",
                f"- **Signal**: {it.signal.signal_id} ({it.signal.kind.value})",
                f"- **Severity**: {it.signal.severity.value}",
                f"- **Summary**: {it.summary}",
                f"- **Decision Hash**: `{it.decision_hash}`",
                f"- **Started**: {it.started_at}",
                f"- **Completed**: {it.completed_at}",
                "",
            ])
            if it.revision_changes:
                lines.append("**Changes:**")
                for ch in it.revision_changes:
                    lines.append(f"  - {ch}")
                lines.append("")
            if it.new_handoff:
                lines.append("New handoff generated.")
                lines.append("")
    # Signals section
    lines.extend([
        "## Signals Processed",
        "",
    ])
    if not episode.signals:
        lines.append("No signals processed.")
        lines.append("")
    else:
        for fp in episode.signals:
            lines.append(f"- `{fp}`")
        lines.append("")
    # Blocked / exhausted info
    if episode.status == LoopStatus.BLOCKED:
        lines.extend([
            "## ⚠️ Blocked",
            "",
            "This episode is blocked and requires human intervention.",
            "",
        ])
    if episode.status == LoopStatus.FAILED:
        lines.extend([
            "## ❌ Failed",
            "",
            "This episode has failed. Check error logs or retry.",
            "",
        ])
    # Footer
    lines.extend([
        "---",
        "",
        f"Generated by Project Forge Loop Engine v0.4.0 at {datetime.utcnow().isoformat()}",
        "",
    ])
    return "\n".join(lines)


def save_report(
    episode: LoopEpisode, project_dir: Path, output_dir: Optional[Path] = None
) -> Path:
    """Save the LOOP report to docs/loop/."""
    target_dir = output_dir or (project_dir / "docs" / "loop")
    target_dir.mkdir(parents=True, exist_ok=True)
    report_text = render_report(episode, project_dir)
    path = target_dir / f"LOOP-{episode.episode_id}.md"
    path.write_text(report_text, encoding="utf-8", newline="\n")
    return path
