"""Render inventory artifacts without changing application source files."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable, Tuple

from .models import ArchitectureInventory, Service


def _cell(values: Iterable[object]) -> str:
    text = ", ".join(str(value) for value in values) or "-"
    return text.replace("|", "\\|").replace("\n", " ")


def _node_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value)
    return "n_" + (cleaned or "unknown")


def _label(value: str) -> str:
    return value.replace('"', "'").replace("\n", " ")


def _service_row(service: Service) -> str:
    return (
        f"| `{service.path}` | {service.kind} | {_cell(service.frameworks)} | "
        f"{_cell(service.entrypoints)} | {_cell(service.ports)} |"
    )


def render_mermaid(inventory: ArchitectureInventory) -> str:
    """Build a conservative topology from detected services and resources."""

    lines = ["flowchart LR"]
    for service in inventory.services:
        lines.append(f'  {_node_id(service.id)}["{_label(service.name)}"]')
    for database in inventory.databases:
        lines.append(f'  {_node_id("db_" + database)}[("{_label(database)}")]')
    for queue in inventory.queues:
        lines.append(f'  {_node_id("queue_" + queue)}{{"{_label(queue)}"}}')
    for integration in inventory.integrations:
        lines.append(f'  {_node_id("integration_" + integration)}["{_label(integration)}"]')
    for relationship in inventory.relationships:
        lines.append(
            f"  {_node_id(relationship.source)} -->|{_label(relationship.kind)}| "
            f"{_node_id(relationship.target)}"
        )
    if len(lines) == 1:
        lines.append('  project["No services detected"]')
    return "\n".join(lines)


def render_markdown(inventory: ArchitectureInventory) -> str:
    """Render a human-readable inventory with a Mermaid topology."""

    service_rows = "\n".join(_service_row(item) for item in inventory.services)
    if not service_rows:
        service_rows = "| - | unknown | - | - | - |"
    workspace_rows = "\n".join(
        f"| `{item.path}` | `{item.source}` |" for item in inventory.workspaces
    ) or "| - | - |"
    warnings = "\n".join(f"- {item}" for item in inventory.warnings) or "- None"
    return f"""# Architecture Inventory

Generated by Project Forge using static file inspection only. No project commands were executed.

## Summary

- Project: **{inventory.project_name}**
- Monorepo: **{'yes' if inventory.monorepo else 'no'}**
- Services: **{len(inventory.services)}**
- Databases: {_cell(inventory.databases)}
- Queues: {_cell(inventory.queues)}
- Third-party integrations: {_cell(inventory.integrations)}

## Workspaces

| Path | Declared by |
| --- | --- |
{workspace_rows}

## Services

| Path | Kind | Frameworks | Entrypoints | Ports |
| --- | --- | --- | --- | --- |
{service_rows}

## Infrastructure

- Docker: {_cell(inventory.docker_files)}
- Compose: {_cell(inventory.compose_files)}
- CI: {_cell(inventory.ci_files)}
- Deployment: {_cell(inventory.deploy_files)}
- Environment variable names: {_cell(inventory.environment_variables)}

## Topology

```mermaid
{render_mermaid(inventory)}
```

## Warnings

{warnings}
"""


def write_inventory(
    inventory: ArchitectureInventory, output_dir: Path
) -> Tuple[Path, Path]:
    """Write the two documented inventory artifacts."""

    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "inventory.json"
    markdown_path = output_dir / "inventory.md"
    json_path.write_text(
        json.dumps(inventory.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    markdown_path.write_text(render_markdown(inventory), encoding="utf-8")
    return json_path, markdown_path
