"""Generate a one-page executive summary from creative decision + ADR + effort estimate.

Target audience: non-technical stakeholders who need to understand why the architecture
was chosen, how long it will take, and what the main risks are.
"""
import argparse, json, sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = str(REPO_ROOT / "src")
sys.path.insert(0, SRC)


def _load_if(path: Path) -> dict:
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8-sig"))


def generate_summary(project_dir=".") -> str:
    project = Path(project_dir)
    creative = _load_if(project / "docs" / "product" / "creative-decision.json")
    handoff = _load_if(project / "docs" / "superpowers-handoff.json")
    adr_path = project / "docs" / "architecture" / "ADR-0001-stack.md"
    adr_text = adr_path.read_text(encoding="utf-8-sig") if adr_path.is_file() else ""

    # Gather data
    goal = handoff.get("project", {}).get("goal") or creative.get("goal") or "Untitled project"
    slug = handoff.get("project", {}).get("slug") or creative.get("selected_direction_id", "unknown")
    primary_stack = handoff.get("project", {}).get("primary_stack", "unknown")
    secondary = handoff.get("project", {}).get("secondary_stacks", [])
    readiness = handoff.get("readiness", {}).get("status", "unknown")
    evidence_count = len(handoff.get("evidence", []))
    inv = handoff.get("inventory") or {}
    services_count = len(inv.get("services", []))
    risks = handoff.get("risks", []) if isinstance(handoff.get("risks"), list) else []

    # Extract selected direction
    selected_dir = creative.get("selected_direction") or {}
    direction_name = selected_dir.get("name", "Not yet selected")
    audience = selected_dir.get("audience", "Not defined")

    # Effort from handoff
    effort = handoff.get("effort_estimate") or {}
    dev_days = effort.get("development_days", "Unknown")
    team = effort.get("team_size_recommendation", "TBD")
    cost = effort.get("infrastructure_cost_tier", "unknown")

    lines = [
        f"# Executive Summary: {slug}",
        "",
        f"> Prepared: {date.today().isoformat()} | Status: {readiness}",
        "",
        "## What We Are Building",
        "",
        goal,
        "",
        f"**Target audience:** {audience}",
        "",
        "## Product Direction",
        "",
        f"Selected direction: **{direction_name}**",
        f"Rationale: {selected_dir.get('reason', 'Not recorded')}",
        "",
        "## Architecture",
        "",
        f"- **Primary stack:** `{primary_stack}`",
    ]
    if secondary:
        lines.append(f"- **Secondary stacks:** {', '.join('`' + s + '`' for s in secondary)}")
    lines.extend([
        f"- **Services detected:** {services_count}",
        f"- **Evidence sources:** {evidence_count}",
        "",
        "## Effort Estimate",
        "",
        f"- **Development days:** {dev_days}",
        f"- **Team size:** {team}",
        f"- **Infrastructure cost tier:** {cost}",
        "",
        "## Key Risks",
        "",
    ])
    if risks:
        for r in risks[:5]:
            lines.append(f"- **{r.get('id', '?')}** ({r.get('likelihood', '?')} likelihood / {r.get('impact', '?')} impact): {r.get('description', '')}")
    else:
        lines.append("- No formal risks registered. Run `project-forge revise` to generate risk analysis.")

    lines.extend([
        "",
        "## Readiness",
        "",
        f"- **Handoff status:** {readiness}",
        f"- Ready for Superpowers implementation: {'Yes' if readiness in ('verified', 'structurally_ready') else 'Review needed'}",
        "",
        "## Next Steps",
        "",
        "1. Hand this summary to the implementation team (or Superpowers).",
        "2. Do not change architecture without running `project-forge revise`.",
        "3. After implementation, run `project-forge verify-implementation` to audit.",
        "",
        "---",
        "",
        f"*Generated by Project Forge v0.3.3 at {date.today().isoformat()}*",
        "",
    ])
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("project", nargs="?", default=".")
    p.add_argument("--out", help="Output file (default: docs/executive-summary.md)")
    args = p.parse_args()
    project = Path(args.project)
    summary = generate_summary(args.project)
    out = Path(args.out or project / "docs" / "executive-summary.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(summary, encoding="utf-8", newline="\n")
    print(f"Executive summary written: {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
